version: '3.8'
services:
  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
  mongo:
    build: ./configs/docker/mongodb
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_REPLICA_HOST: mongo
      MONGO_REPLICA_PORT: 27017
    volumes:
      - mongo-data:/data/db
volumes:
  redis-data:
  mongo-data:
